In [0]:
import numpy as np

# sigmoid activation
def sigmoid(x,deriv=False): 
  if(deriv==True):
    return x*(1-x)
  return 1/(1+np.exp(-x))
    

# input dataset
X = np.array([ [1,1,1,1,1,1,0],
               [0,1,1,0,0,0,0],
               [1,1,0,1,1,0,1],
               [1,1,1,1,0,0,1],
               [0,1,1,0,0,1,1],              
               [1,0,1,1,0,1,1],
               [1,0,1,1,1,1,1],
               [1,1,1,0,0,0,0],
               [1,1,1,1,1,1,1],
               [1,1,1,1,0,1,1] ])
# target output dataset            
Y = np.array([ [1,0,0,0,0,0,0,0,0,0],
               [0,1,0,0,0,0,0,0,0,0],
               [0,0,1,0,0,0,0,0,0,0],
               [0,0,0,1,0,0,0,0,0,0],
               [0,0,0,0,1,0,0,0,0,0],
               [0,0,0,0,0,1,0,0,0,0],
               [0,0,0,0,0,0,1,0,0,0],
               [0,0,0,0,0,0,0,1,0,0],
               [0,0,0,0,0,0,0,0,1,0],
               [0,0,0,0,0,0,0,0,0,1] ])

np.random.seed(1)

# initialize weights randomly with mean 0
w = 2*np.random.random((7,10)) - 1

alpha = 0.3   # learning rate

loss_history = []    # keep a record of how the loss proceeded, blank for now
for iter in range(1000000):

    Y_pred = sigmoid(np.dot(X,w)) # prediction, i.e. tilde{Y}

    # how much did we miss?
    diff = Y_pred - Y
    loss_history.append((diff**2).mean())   # add to the history of the loss

    # update weights
    w -= alpha * np.dot( X.T, diff*sigmoid(Y_pred, deriv=True))
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print("Output After Training:")
print("Y_pred = (should be the 10x10 identity matrix)\n",Y_pred)
print("weights =\n",repr (w))


Output After Training:
Y_pred = (should be two 0's followed by two 1's)
 [[0.998 0.000 0.000 0.000 0.000 0.000 0.001 0.001 0.215 0.002]
 [0.002 0.998 0.000 0.002 0.002 0.000 0.000 0.002 0.002 0.000]
 [0.001 0.000 0.999 0.002 0.000 0.000 0.001 0.001 0.215 0.001]
 [0.000 0.000 0.001 0.997 0.000 0.000 0.000 0.001 0.000 0.003]
 [0.000 0.001 0.000 0.000 0.998 0.000 0.000 0.000 0.215 0.003]
 [0.000 0.000 0.000 0.002 0.001 0.997 0.002 0.001 0.001 0.003]
 [0.002 0.000 0.000 0.000 0.000 0.002 0.997 0.000 0.215 0.000]
 [0.001 0.002 0.000 0.001 0.000 0.000 0.000 0.998 0.000 0.001]
 [0.001 0.000 0.001 0.000 0.000 0.000 0.001 0.000 0.151 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.002 0.000 0.000 0.001 0.995]]
weights =
 array([[-0.478, -12.319, -0.735, -0.553, -7.760, 0.851, -3.831, 12.220,
        -2.980, 1.862],
       [-0.869, 2.789, 0.573, -3.468, -1.156, -12.249, -12.675, -2.949,
        -0.432, 10.929],
       [-5.616, 3.230, -9.040, -2.628, -5.154, 0.415, -0.525, -3.194,
        -5.871, -19.39